import VmExtensions.Soundness.KeccakfPermAir.Round.ChiHelpers
set_option autoImplicit false
set_option linter.all false
set_option maxHeartbeats 32000000
namespace KeccakfPermAir.Soundness
open BabyBear KeccakfPermAir.constraints
variable {ExtF : Type} [Field ExtF]
  {air : KeccakfPermAir.Valid_KeccakfPermAir FBB ExtF} {row : ℕ}

private theorem chi_bridge_0 (h : ChiConstraints air row) : chiCanonicalK air 0 row := h.h2910
private theorem chi_bridge_1 (h : ChiConstraints air row) : chiCanonicalK air 1 row := h.h2911
private theorem chi_bridge_2 (h : ChiConstraints air row) : chiCanonicalK air 2 row := h.h2912
private theorem chi_bridge_3 (h : ChiConstraints air row) : chiCanonicalK air 3 row := h.h2913
private theorem chi_bridge_4 (h : ChiConstraints air row) : chiCanonicalK air 4 row := h.h2914
private theorem chi_bridge_5 (h : ChiConstraints air row) : chiCanonicalK air 5 row := h.h2915
private theorem chi_bridge_6 (h : ChiConstraints air row) : chiCanonicalK air 6 row := h.h2916
private theorem chi_bridge_7 (h : ChiConstraints air row) : chiCanonicalK air 7 row := h.h2917
private theorem chi_bridge_8 (h : ChiConstraints air row) : chiCanonicalK air 8 row := h.h2918
private theorem chi_bridge_9 (h : ChiConstraints air row) : chiCanonicalK air 9 row := h.h2919
private theorem chi_bridge_10 (h : ChiConstraints air row) : chiCanonicalK air 10 row := h.h2920
private theorem chi_bridge_11 (h : ChiConstraints air row) : chiCanonicalK air 11 row := h.h2921
private theorem chi_bridge_12 (h : ChiConstraints air row) : chiCanonicalK air 12 row := h.h2922
private theorem chi_bridge_13 (h : ChiConstraints air row) : chiCanonicalK air 13 row := h.h2923
private theorem chi_bridge_14 (h : ChiConstraints air row) : chiCanonicalK air 14 row := h.h2924
private theorem chi_bridge_15 (h : ChiConstraints air row) : chiCanonicalK air 15 row := h.h2925
private theorem chi_bridge_16 (h : ChiConstraints air row) : chiCanonicalK air 16 row := h.h2926
private theorem chi_bridge_17 (h : ChiConstraints air row) : chiCanonicalK air 17 row := h.h2927
private theorem chi_bridge_18 (h : ChiConstraints air row) : chiCanonicalK air 18 row := h.h2928
private theorem chi_bridge_19 (h : ChiConstraints air row) : chiCanonicalK air 19 row := h.h2929
private theorem chi_bridge_20 (h : ChiConstraints air row) : chiCanonicalK air 20 row := h.h2930
private theorem chi_bridge_21 (h : ChiConstraints air row) : chiCanonicalK air 21 row := h.h2931
private theorem chi_bridge_22 (h : ChiConstraints air row) : chiCanonicalK air 22 row := h.h2932
private theorem chi_bridge_23 (h : ChiConstraints air row) : chiCanonicalK air 23 row := h.h2933
private theorem chi_bridge_24 (h : ChiConstraints air row) : chiCanonicalK air 24 row := h.h2934
private theorem chi_bridge_25 (h : ChiConstraints air row) : chiCanonicalK air 25 row := h.h2935
private theorem chi_bridge_26 (h : ChiConstraints air row) : chiCanonicalK air 26 row := h.h2936
private theorem chi_bridge_27 (h : ChiConstraints air row) : chiCanonicalK air 27 row := h.h2937
private theorem chi_bridge_28 (h : ChiConstraints air row) : chiCanonicalK air 28 row := h.h2938
private theorem chi_bridge_29 (h : ChiConstraints air row) : chiCanonicalK air 29 row := h.h2939
private theorem chi_bridge_30 (h : ChiConstraints air row) : chiCanonicalK air 30 row := h.h2940
private theorem chi_bridge_31 (h : ChiConstraints air row) : chiCanonicalK air 31 row := h.h2941
private theorem chi_bridge_32 (h : ChiConstraints air row) : chiCanonicalK air 32 row := h.h2942
private theorem chi_bridge_33 (h : ChiConstraints air row) : chiCanonicalK air 33 row := h.h2943
private theorem chi_bridge_34 (h : ChiConstraints air row) : chiCanonicalK air 34 row := h.h2944
private theorem chi_bridge_35 (h : ChiConstraints air row) : chiCanonicalK air 35 row := h.h2945
private theorem chi_bridge_36 (h : ChiConstraints air row) : chiCanonicalK air 36 row := h.h2946
private theorem chi_bridge_37 (h : ChiConstraints air row) : chiCanonicalK air 37 row := h.h2947
private theorem chi_bridge_38 (h : ChiConstraints air row) : chiCanonicalK air 38 row := h.h2948
private theorem chi_bridge_39 (h : ChiConstraints air row) : chiCanonicalK air 39 row := h.h2949
private theorem chi_bridge_40 (h : ChiConstraints air row) : chiCanonicalK air 40 row := h.h2950
private theorem chi_bridge_41 (h : ChiConstraints air row) : chiCanonicalK air 41 row := h.h2951
private theorem chi_bridge_42 (h : ChiConstraints air row) : chiCanonicalK air 42 row := h.h2952
private theorem chi_bridge_43 (h : ChiConstraints air row) : chiCanonicalK air 43 row := h.h2953
private theorem chi_bridge_44 (h : ChiConstraints air row) : chiCanonicalK air 44 row := h.h2954
private theorem chi_bridge_45 (h : ChiConstraints air row) : chiCanonicalK air 45 row := h.h2955
private theorem chi_bridge_46 (h : ChiConstraints air row) : chiCanonicalK air 46 row := h.h2956
private theorem chi_bridge_47 (h : ChiConstraints air row) : chiCanonicalK air 47 row := h.h2957
private theorem chi_bridge_48 (h : ChiConstraints air row) : chiCanonicalK air 48 row := h.h2958
private theorem chi_bridge_49 (h : ChiConstraints air row) : chiCanonicalK air 49 row := h.h2959
private theorem chi_bridge_50 (h : ChiConstraints air row) : chiCanonicalK air 50 row := h.h2960
private theorem chi_bridge_51 (h : ChiConstraints air row) : chiCanonicalK air 51 row := h.h2961
private theorem chi_bridge_52 (h : ChiConstraints air row) : chiCanonicalK air 52 row := h.h2962
private theorem chi_bridge_53 (h : ChiConstraints air row) : chiCanonicalK air 53 row := h.h2963
private theorem chi_bridge_54 (h : ChiConstraints air row) : chiCanonicalK air 54 row := h.h2964
private theorem chi_bridge_55 (h : ChiConstraints air row) : chiCanonicalK air 55 row := h.h2965
private theorem chi_bridge_56 (h : ChiConstraints air row) : chiCanonicalK air 56 row := h.h2966
private theorem chi_bridge_57 (h : ChiConstraints air row) : chiCanonicalK air 57 row := h.h2967
private theorem chi_bridge_58 (h : ChiConstraints air row) : chiCanonicalK air 58 row := h.h2968
private theorem chi_bridge_59 (h : ChiConstraints air row) : chiCanonicalK air 59 row := h.h2969
private theorem chi_bridge_60 (h : ChiConstraints air row) : chiCanonicalK air 60 row := h.h2970
private theorem chi_bridge_61 (h : ChiConstraints air row) : chiCanonicalK air 61 row := h.h2971
private theorem chi_bridge_62 (h : ChiConstraints air row) : chiCanonicalK air 62 row := h.h2972
private theorem chi_bridge_63 (h : ChiConstraints air row) : chiCanonicalK air 63 row := h.h2973
private theorem chi_bridge_64 (h : ChiConstraints air row) : chiCanonicalK air 64 row := h.h2974
private theorem chi_bridge_65 (h : ChiConstraints air row) : chiCanonicalK air 65 row := h.h2975
private theorem chi_bridge_66 (h : ChiConstraints air row) : chiCanonicalK air 66 row := h.h2976
private theorem chi_bridge_67 (h : ChiConstraints air row) : chiCanonicalK air 67 row := h.h2977
private theorem chi_bridge_68 (h : ChiConstraints air row) : chiCanonicalK air 68 row := h.h2978
private theorem chi_bridge_69 (h : ChiConstraints air row) : chiCanonicalK air 69 row := h.h2979
private theorem chi_bridge_70 (h : ChiConstraints air row) : chiCanonicalK air 70 row := h.h2980
private theorem chi_bridge_71 (h : ChiConstraints air row) : chiCanonicalK air 71 row := h.h2981
private theorem chi_bridge_72 (h : ChiConstraints air row) : chiCanonicalK air 72 row := h.h2982
private theorem chi_bridge_73 (h : ChiConstraints air row) : chiCanonicalK air 73 row := h.h2983
private theorem chi_bridge_74 (h : ChiConstraints air row) : chiCanonicalK air 74 row := h.h2984
private theorem chi_bridge_75 (h : ChiConstraints air row) : chiCanonicalK air 75 row := h.h2985
private theorem chi_bridge_76 (h : ChiConstraints air row) : chiCanonicalK air 76 row := h.h2986
private theorem chi_bridge_77 (h : ChiConstraints air row) : chiCanonicalK air 77 row := h.h2987
private theorem chi_bridge_78 (h : ChiConstraints air row) : chiCanonicalK air 78 row := h.h2988
private theorem chi_bridge_79 (h : ChiConstraints air row) : chiCanonicalK air 79 row := h.h2989
private theorem chi_bridge_80 (h : ChiConstraints air row) : chiCanonicalK air 80 row := h.h2990
private theorem chi_bridge_81 (h : ChiConstraints air row) : chiCanonicalK air 81 row := h.h2991
private theorem chi_bridge_82 (h : ChiConstraints air row) : chiCanonicalK air 82 row := h.h2992
private theorem chi_bridge_83 (h : ChiConstraints air row) : chiCanonicalK air 83 row := h.h2993
private theorem chi_bridge_84 (h : ChiConstraints air row) : chiCanonicalK air 84 row := h.h2994
private theorem chi_bridge_85 (h : ChiConstraints air row) : chiCanonicalK air 85 row := h.h2995
private theorem chi_bridge_86 (h : ChiConstraints air row) : chiCanonicalK air 86 row := h.h2996
private theorem chi_bridge_87 (h : ChiConstraints air row) : chiCanonicalK air 87 row := h.h2997
private theorem chi_bridge_88 (h : ChiConstraints air row) : chiCanonicalK air 88 row := h.h2998
private theorem chi_bridge_89 (h : ChiConstraints air row) : chiCanonicalK air 89 row := h.h2999
private theorem chi_bridge_90 (h : ChiConstraints air row) : chiCanonicalK air 90 row := h.h3000
private theorem chi_bridge_91 (h : ChiConstraints air row) : chiCanonicalK air 91 row := h.h3001
private theorem chi_bridge_92 (h : ChiConstraints air row) : chiCanonicalK air 92 row := h.h3002
private theorem chi_bridge_93 (h : ChiConstraints air row) : chiCanonicalK air 93 row := h.h3003
private theorem chi_bridge_94 (h : ChiConstraints air row) : chiCanonicalK air 94 row := h.h3004
private theorem chi_bridge_95 (h : ChiConstraints air row) : chiCanonicalK air 95 row := h.h3005
private theorem chi_bridge_96 (h : ChiConstraints air row) : chiCanonicalK air 96 row := h.h3006
private theorem chi_bridge_97 (h : ChiConstraints air row) : chiCanonicalK air 97 row := h.h3007
private theorem chi_bridge_98 (h : ChiConstraints air row) : chiCanonicalK air 98 row := h.h3008
private theorem chi_bridge_99 (h : ChiConstraints air row) : chiCanonicalK air 99 row := h.h3009

noncomputable def chi_canonical_of_chi
    (h : ChiConstraints air row) (n : Fin 100) : chiCanonicalK air n.val row :=
  match n with
  | ⟨0, _⟩ => chi_bridge_0 h
  | ⟨1, _⟩ => chi_bridge_1 h
  | ⟨2, _⟩ => chi_bridge_2 h
  | ⟨3, _⟩ => chi_bridge_3 h
  | ⟨4, _⟩ => chi_bridge_4 h
  | ⟨5, _⟩ => chi_bridge_5 h
  | ⟨6, _⟩ => chi_bridge_6 h
  | ⟨7, _⟩ => chi_bridge_7 h
  | ⟨8, _⟩ => chi_bridge_8 h
  | ⟨9, _⟩ => chi_bridge_9 h
  | ⟨10, _⟩ => chi_bridge_10 h
  | ⟨11, _⟩ => chi_bridge_11 h
  | ⟨12, _⟩ => chi_bridge_12 h
  | ⟨13, _⟩ => chi_bridge_13 h
  | ⟨14, _⟩ => chi_bridge_14 h
  | ⟨15, _⟩ => chi_bridge_15 h
  | ⟨16, _⟩ => chi_bridge_16 h
  | ⟨17, _⟩ => chi_bridge_17 h
  | ⟨18, _⟩ => chi_bridge_18 h
  | ⟨19, _⟩ => chi_bridge_19 h
  | ⟨20, _⟩ => chi_bridge_20 h
  | ⟨21, _⟩ => chi_bridge_21 h
  | ⟨22, _⟩ => chi_bridge_22 h
  | ⟨23, _⟩ => chi_bridge_23 h
  | ⟨24, _⟩ => chi_bridge_24 h
  | ⟨25, _⟩ => chi_bridge_25 h
  | ⟨26, _⟩ => chi_bridge_26 h
  | ⟨27, _⟩ => chi_bridge_27 h
  | ⟨28, _⟩ => chi_bridge_28 h
  | ⟨29, _⟩ => chi_bridge_29 h
  | ⟨30, _⟩ => chi_bridge_30 h
  | ⟨31, _⟩ => chi_bridge_31 h
  | ⟨32, _⟩ => chi_bridge_32 h
  | ⟨33, _⟩ => chi_bridge_33 h
  | ⟨34, _⟩ => chi_bridge_34 h
  | ⟨35, _⟩ => chi_bridge_35 h
  | ⟨36, _⟩ => chi_bridge_36 h
  | ⟨37, _⟩ => chi_bridge_37 h
  | ⟨38, _⟩ => chi_bridge_38 h
  | ⟨39, _⟩ => chi_bridge_39 h
  | ⟨40, _⟩ => chi_bridge_40 h
  | ⟨41, _⟩ => chi_bridge_41 h
  | ⟨42, _⟩ => chi_bridge_42 h
  | ⟨43, _⟩ => chi_bridge_43 h
  | ⟨44, _⟩ => chi_bridge_44 h
  | ⟨45, _⟩ => chi_bridge_45 h
  | ⟨46, _⟩ => chi_bridge_46 h
  | ⟨47, _⟩ => chi_bridge_47 h
  | ⟨48, _⟩ => chi_bridge_48 h
  | ⟨49, _⟩ => chi_bridge_49 h
  | ⟨50, _⟩ => chi_bridge_50 h
  | ⟨51, _⟩ => chi_bridge_51 h
  | ⟨52, _⟩ => chi_bridge_52 h
  | ⟨53, _⟩ => chi_bridge_53 h
  | ⟨54, _⟩ => chi_bridge_54 h
  | ⟨55, _⟩ => chi_bridge_55 h
  | ⟨56, _⟩ => chi_bridge_56 h
  | ⟨57, _⟩ => chi_bridge_57 h
  | ⟨58, _⟩ => chi_bridge_58 h
  | ⟨59, _⟩ => chi_bridge_59 h
  | ⟨60, _⟩ => chi_bridge_60 h
  | ⟨61, _⟩ => chi_bridge_61 h
  | ⟨62, _⟩ => chi_bridge_62 h
  | ⟨63, _⟩ => chi_bridge_63 h
  | ⟨64, _⟩ => chi_bridge_64 h
  | ⟨65, _⟩ => chi_bridge_65 h
  | ⟨66, _⟩ => chi_bridge_66 h
  | ⟨67, _⟩ => chi_bridge_67 h
  | ⟨68, _⟩ => chi_bridge_68 h
  | ⟨69, _⟩ => chi_bridge_69 h
  | ⟨70, _⟩ => chi_bridge_70 h
  | ⟨71, _⟩ => chi_bridge_71 h
  | ⟨72, _⟩ => chi_bridge_72 h
  | ⟨73, _⟩ => chi_bridge_73 h
  | ⟨74, _⟩ => chi_bridge_74 h
  | ⟨75, _⟩ => chi_bridge_75 h
  | ⟨76, _⟩ => chi_bridge_76 h
  | ⟨77, _⟩ => chi_bridge_77 h
  | ⟨78, _⟩ => chi_bridge_78 h
  | ⟨79, _⟩ => chi_bridge_79 h
  | ⟨80, _⟩ => chi_bridge_80 h
  | ⟨81, _⟩ => chi_bridge_81 h
  | ⟨82, _⟩ => chi_bridge_82 h
  | ⟨83, _⟩ => chi_bridge_83 h
  | ⟨84, _⟩ => chi_bridge_84 h
  | ⟨85, _⟩ => chi_bridge_85 h
  | ⟨86, _⟩ => chi_bridge_86 h
  | ⟨87, _⟩ => chi_bridge_87 h
  | ⟨88, _⟩ => chi_bridge_88 h
  | ⟨89, _⟩ => chi_bridge_89 h
  | ⟨90, _⟩ => chi_bridge_90 h
  | ⟨91, _⟩ => chi_bridge_91 h
  | ⟨92, _⟩ => chi_bridge_92 h
  | ⟨93, _⟩ => chi_bridge_93 h
  | ⟨94, _⟩ => chi_bridge_94 h
  | ⟨95, _⟩ => chi_bridge_95 h
  | ⟨96, _⟩ => chi_bridge_96 h
  | ⟨97, _⟩ => chi_bridge_97 h
  | ⟨98, _⟩ => chi_bridge_98 h
  | ⟨99, _⟩ => chi_bridge_99 h
  | ⟨n + 100, hn⟩ => absurd hn (by omega)
end KeccakfPermAir.Soundness
