name = "openvm-fv"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["OpenvmFv"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3
# linter.hashCommand = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0-rc2"

[[require]]
name = "LeanZKCircuit"
git = "https://github.com/NethermindEth/leanzkcircuit.git"
rev = "Dom/openvm_prelude"

[[require]]
name = "LeanRV"
git = "https://github.com/NethermindEth/sail-riscv-lean"
rev = "rv32d"

[[lean_lib]]
name = "OpenvmFv"
