name = "openvm-fv"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["OpenvmFv"]
moreLeanArgs = ["--tstack=400000"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3
# linter.hashCommand = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0-rc2"

[[require]]
name = "LeanZKCircuit"
git = "https://github.com/NethermindEth/leanzkcircuit.git"
rev = "main"

[[require]]
name = "LeanRV"
git = "https://github.com/NethermindEth/sail-riscv-lean"
rev = "511e25600eb89f1d4a73e2a3b5e6fda7a0622757"

[[lean_lib]]
name = "OpenvmFv"
