name = "openvm-fv"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["OpenvmFv"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3
# linter.hashCommand = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "LeanZKCircuit"
git = "https://github.com/NethermindEth/leanzkcircuit.git"
rev = "Dom/openvm_prelude"

[[lean_lib]]
name = "OpenvmFv"
