import Mathlib

import LeanZKCircuit.OpenVM.Circuit

set_option linter.all false

register_simp_attr VmAirWrapper_auipc_air_simplification
register_simp_attr VmAirWrapper_auipc_constraint_and_interaction_simplification

namespace VmAirWrapper_auipc.extraction

  --extracted constraints here
  @[simp]
  def constraint_0 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
    ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)) * ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)) - 1)) = 0

  @[simp]
  def constraint_1 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
    ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)) * ((2005401601 * ((((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0))) + 0)) * ((2005401601 * ((((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0))) + 0)) - 1))) = 0

  @[simp]
  def constraint_2 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
    ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)) * ((2005401601 * ((((Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 12) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 18) (row := row) (rotation := 0))) + (2005401601 * ((((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0))) + 0)))) * ((2005401601 * ((((Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 12) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 18) (row := row) (rotation := 0))) + (2005401601 * ((((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0))) + 0)))) - 1))) = 0

  @[simp]
  def constraint_3 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
    ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)) * ((2005401601 * ((((((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) - ((Circuit.main c (id := 0) (column := 16) (row := row) (rotation := 0)) + ((0 + ((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) * 256)) + ((Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)) * 65536)))) * 2013265801) + (Circuit.main c (id := 0) (column := 13) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 19) (row := row) (rotation := 0))) + (2005401601 * ((((Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 12) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 18) (row := row) (rotation := 0))) + (2005401601 * ((((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0))) + 0)))))) * ((2005401601 * ((((((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) - ((Circuit.main c (id := 0) (column := 16) (row := row) (rotation := 0)) + ((0 + ((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) * 256)) + ((Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)) * 65536)))) * 2013265801) + (Circuit.main c (id := 0) (column := 13) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 19) (row := row) (rotation := 0))) + (2005401601 * ((((Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 12) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 18) (row := row) (rotation := 0))) + (2005401601 * ((((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) + (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0))) - (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0))) + 0)))))) - 1))) = 0

  @[simp]
  def constraint_4 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
    ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)) * ((((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) - (Circuit.main c (id := 0) (column := 3) (row := row) (rotation := 0))) - 1) - ((0 + ((Circuit.main c (id := 0) (column := 4) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 5) (row := row) (rotation := 0)) * 131072)))) = 0

  def constrain_interactions {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) :=
    Circuit.buses c = λ index =>
      if index = 0 then (List.range (Circuit.last_row c + 1)).flatMap (λ row => [(-((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0))), [(Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0))]), ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) + 4), ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) + 1)])])
      else if index = 1 then (List.range (Circuit.last_row c + 1)).flatMap (λ row => [((2013265920 * (Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0))), [1, (Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 9) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 3) (row := row) (rotation := 0))]), ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [1, (Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 16) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 18) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 19) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0))])])
      else if index = 4 then (List.range (Circuit.last_row c + 1)).flatMap (λ row => [((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 4) (row := row) (rotation := 0)), 17]), ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 5) (row := row) (rotation := 0)), 12])])
      else if index = 8 then (List.range (Circuit.last_row c + 1)).flatMap (λ row => [((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)), (576 + 0), (Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)), 0, (((0 + ((Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 12) (row := row) (rotation := 0)) * 256)) + ((Circuit.main c (id := 0) (column := 13) (row := row) (rotation := 0)) * 65536)), 1, 0, 0, 0])])
      else if index = 9 then (List.range (Circuit.last_row c + 1)).flatMap (λ row => [((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 16) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 17) (row := row) (rotation := 0)), 0, 0]), ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 18) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 19) (row := row) (rotation := 0)), 0, 0]), ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 12) (row := row) (rotation := 0)), 0, 0]), ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 13) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)), 0, 0]), ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), [(Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)), ((((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) - ((Circuit.main c (id := 0) (column := 16) (row := row) (rotation := 0)) + ((0 + ((Circuit.main c (id := 0) (column := 14) (row := row) (rotation := 0)) * 256)) + ((Circuit.main c (id := 0) (column := 15) (row := row) (rotation := 0)) * 65536)))) * 2013265801) * 4), 0, 0])])
    else []

end VmAirWrapper_auipc.extraction
