import Mathlib

import LeanZKCircuit.OpenVM.Circuit

set_option linter.all false

namespace VolatileBoundaryAir.extraction

def constraint_0 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)) * ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)) - 1)) = 0

def constraint_1 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((((1 - (Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1))) + (Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0))) - ((1 - (Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1))) * (Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)))) - 1)) = 0

def constraint_2 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0)) * ((Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0)) - 1))) = 0

def constraint_3 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)) * ((1 - (0 + (Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0)))) * ((0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 1)) * 1)) - (0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1)))))) = 0

def constraint_4 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0)) * ((((0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 1)) * 1)) - (0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1))) * (Circuit.main c (id := 0) (column := 9) (row := row) (rotation := 0))) - 1))) = 0

def constraint_5 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0)) * ((Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0)) - 1))) = 0

def constraint_6 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)) * ((1 - ((0 + (Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0))) + (Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0)))) * (((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 1)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 1)) * 131072)) - ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072)))))) = 0

def constraint_7 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0)) * (((((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 1)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 1)) * 131072)) - ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072))) * (Circuit.main c (id := 0) (column := 9) (row := row) (rotation := 0))) - 1))) = 0

def constraint_8 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * (((0 + (Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0))) + (Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0))) * (((0 + (Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0))) + (Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0))) - 1))) = 0

def constraint_9 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)) * ((1 - ((0 + (Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0))) + (Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0)))) * 1))) = 0

def constraint_10 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)) * ((((0 + (((0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 1)) * 1)) - (0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1))) * (Circuit.main c (id := 0) (column := 7) (row := row) (rotation := 0)))) + ((((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 1)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 1)) * 131072)) - ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072))) * (Circuit.main c (id := 0) (column := 8) (row := row) (rotation := 0)))) + 536870911) - (((0 + ((Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0)) * 131072)) + (1 * 536870912))))) = 0

def constraint_11 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
  ((Circuit.isTransitionRow c row) * (1 * (1 - 1))) = 0

-- def constraint_12 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
--   ((((Circuit.permutation c (column := 0) (row := row) (rotation := 0)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 4)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 17)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))) - ((0 + ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 17)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0))))) + ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 4)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))))) = 0

-- def constraint_13 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
--   ((((Circuit.permutation c (column := 1) (row := row) (rotation := 0)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 12)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 17)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))) - ((0 + ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 17)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0))))) + ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 12)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))))) = 0

-- def constraint_14 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
--   ((((Circuit.permutation c (column := 2) (row := row) (rotation := 0)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 12)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))) * ((((((0 + (1 * (0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1)))) + ((1 * (Circuit.challenge c (index := 1))) * ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072)))) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.main c (id := 0) (column := 3) (row := row) (rotation := 0)))) + ((((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 0)) + (((((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 2)) + (Circuit.challenge c (index := 0)))) - ((0 + ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)) * ((((((0 + (1 * (0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1)))) + ((1 * (Circuit.challenge c (index := 1))) * ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072)))) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.main c (id := 0) (column := 3) (row := row) (rotation := 0)))) + ((((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 0)) + (((((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 2)) + (Circuit.challenge c (index := 0))))) + ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)) * ((((0 + (1 * (Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0)))) + ((1 * (Circuit.challenge c (index := 1))) * 12)) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 5)) + (Circuit.challenge c (index := 0)))))) = 0

-- def constraint_15 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
--   (((Circuit.permutation c (column := 3) (row := row) (rotation := 0)) * ((((((0 + (1 * (0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1)))) + ((1 * (Circuit.challenge c (index := 1))) * ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072)))) + (((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.main c (id := 0) (column := 4) (row := row) (rotation := 0)))) + ((((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.main c (id := 0) (column := 5) (row := row) (rotation := 0)))) + (((((1 * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * (Circuit.challenge c (index := 1))) * 2)) + (Circuit.challenge c (index := 0)))) - (0 + (2013265920 * (Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0))))) = 0

-- def constraint_16 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
--   ((((Circuit.permutation c (column := 4) (row := row) (rotation := 1)) - (Circuit.permutation c (column := 4) (row := row) (rotation := 0))) - ((((0 + (Circuit.permutation c (column := 0) (row := row) (rotation := 1))) + (Circuit.permutation c (column := 1) (row := row) (rotation := 1))) + (Circuit.permutation c (column := 2) (row := row) (rotation := 1))) + (Circuit.permutation c (column := 3) (row := row) (rotation := 1)))) * (Circuit.isTransitionRow c row)) = 0

-- def constraint_17 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
--   (((Circuit.permutation c (column := 4) (row := row) (rotation := 0)) - ((((0 + (Circuit.permutation c (column := 0) (row := row) (rotation := 0))) + (Circuit.permutation c (column := 1) (row := row) (rotation := 0))) + (Circuit.permutation c (column := 2) (row := row) (rotation := 0))) + (Circuit.permutation c (column := 3) (row := row) (rotation := 0)))) * (Circuit.isFirstRow c row)) = 0

-- def constraint_18 {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) (row: ℕ) :=
--   (((Circuit.permutation c (column := 4) (row := row) (rotation := 0)) - (Circuitc.exposed c (index := 0))) * (Circuit.isLastRow c row)) = 0

def constrain_interactions {C : Type → Type → Type} {F ExtF : Type} [Field F] [Field ExtF] [Circuit F ExtF C] (c : C F ExtF) :=
  Circuit.buses c = λ index =>
    if index = 1 then (([].append ((List.range (Circuit.last_row c + 1)).map (λ row => ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)),[(0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1)), ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072)), (Circuit.main c (id := 0) (column := 3) (row := row) (rotation := 0)), 0])))).append ((List.range (Circuit.last_row c + 1)).map (λ row => ((2013265920 * (Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0))),[(0 + ((Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)) * 1)), ((0 + ((Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)) * 1)) + ((Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)) * 131072)), (Circuit.main c (id := 0) (column := 4) (row := row) (rotation := 0)), (Circuit.main c (id := 0) (column := 5) (row := row) (rotation := 0))]))))
    else if index = 4 then ((((([].append ((List.range (Circuit.last_row c + 1)).map (λ row => ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)),[(Circuit.main c (id := 0) (column := 0) (row := row) (rotation := 0)), 4])))).append ((List.range (Circuit.last_row c + 1)).map (λ row => ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)),[(Circuit.main c (id := 0) (column := 1) (row := row) (rotation := 0)), 17])))).append ((List.range (Circuit.last_row c + 1)).map (λ row => ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 0)),[(Circuit.main c (id := 0) (column := 2) (row := row) (rotation := 0)), 12])))).append ((List.range (Circuit.last_row c + 1)).map (λ row => ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)),[(Circuit.main c (id := 0) (column := 10) (row := row) (rotation := 0)), 17])))).append ((List.range (Circuit.last_row c + 1)).map (λ row => ((Circuit.main c (id := 0) (column := 6) (row := row) (rotation := 1)),[(Circuit.main c (id := 0) (column := 11) (row := row) (rotation := 0)), 12]))))
    else []

end VolatileBoundaryAir.extraction
