name: Lean Action CI

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on:
      - runs-on=${{ github.run_id }}/disk=large/runner=64cpu-linux-x64/image=ubuntu24-full-x64/extras=s3-cache

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
